### ISSUE TITLE
UnsupportedOperation error with 2.1.0

### ISSUE THREAD

**Issue by href** [jonashaag/bjoern#130]
I've upgraded Bjoern to 2.1.0 from 2.0.5 and started to get the following errors in my code:

<details>
  <summary>The full traceback</summary>

```python
Traceback (most recent call last):
  File "/opt/onegov-applications/lib/python3.6/site-packages/onegov/server/core.py", line 167, in __call__
    return self.handle_request(environ, start_response)
  File "/opt/onegov-applications/lib/python3.6/site-packages/onegov/server/core.py", line 163, in handle_request
    return application(environ, start_response)
  File "/opt/onegov-applications/lib/python3.6/site-packages/onegov/core/framework.py", line 129, in with_request_cache_wrapper
    return fn(*args, **kwargs)
  File "/opt/onegov-applications/lib/python3.6/site-packages/onegov/core/framework.py", line 137, in with_print_exceptions_wrapper
    return fn(*args, **kwargs)
  File "/opt/onegov-applications/lib/python3.6/site-packages/morepath/app.py", line 137, in __call__
    response = self.publish(request)
  File "/opt/onegov-applications/lib/python3.6/site-packages/morepath/core.py", line 194, in poisoned_host_header_protection_tween
    return handler(request)
  File "/opt/onegov-applications/lib/python3.6/site-packages/onegov/core/framework.py", line 1124, in http_conflict_tween
    return handler(request)
  File "/opt/onegov-applications/lib/python3.6/site-packages/onegov/search/integration.py", line 334, in process_indexer_tween
    result = handler(request)
  File "/opt/onegov-applications/lib/python3.6/site-packages/onegov/file/integration.py", line 138, in configure_depot_tween
    return handler(request)
  File "/opt/onegov-applications/lib/python3.6/site-packages/more/transaction/main.py", line 67, in transaction_tween
    response = handler(request)
  File "/opt/onegov-applications/lib/python3.6/site-packages/morepath/core.py", line 153, in excview_tween
    response = handler(request)
  File "/opt/onegov-applications/lib/python3.6/site-packages/onegov/core/framework.py", line 1019, in fix_webassets_url
    response = handler(request)
  File "/opt/onegov-applications/lib/python3.6/site-packages/more/webassets/tweens.py", line 132, in __call__
    return self.handler(request)
  File "/opt/onegov-applications/lib/python3.6/site-packages/more/webassets/tweens.py", line 84, in __call__
    response = self.handler(request)
  File "/opt/onegov-applications/lib/python3.6/site-packages/more/content_security/core.py", line 99, in content_security_policy_tween
    response = handler(request)
  File "/opt/onegov-applications/lib/python3.6/site-packages/onegov/core/framework.py", line 1153, in current_language_tween
    return handler(request)
  File "/opt/onegov-applications/lib/python3.6/site-packages/onegov/core/framework.py", line 1184, in spawn_cronjob_thread_tween
    return handler(request)
  File "/opt/onegov-applications/lib/python3.6/site-packages/onegov/gis/integration.py", line 67, in inject_mapbox_api_token_tween
    response = handler(request)
  File "/opt/onegov-applications/lib/python3.6/site-packages/morepath/publish.py", line 39, in publish
    return resolve_response(obj, request)
  File "/opt/onegov-applications/lib/python3.6/site-packages/morepath/publish.py", line 94, in resolve_response
    return request.app.get_view(obj, request)
  File "<generated code: def call(self, obj, request):
    _key = _registry_key(self=self, obj=obj, request=request)
    return (_component_lookup(_key) or
            _fallback_lookup(_key) or
            _fallback)(self, obj, request)
>", line 5, in call
  File "/opt/onegov-applications/lib/python3.6/site-packages/morepath/view.py", line 78, in __call__
    response = self.render(content, request)
  File "/opt/onegov-applications/lib/python3.6/site-packages/onegov/file/integration.py", line 145, in render_depot_file
    FileServeApp(file, cache_max_age=3600 * 24 * 7))
  File "/opt/onegov-applications/lib/python3.6/site-packages/webob/request.py", line 1327, in send
    application, catch_exc_info=False)
  File "/opt/onegov-applications/lib/python3.6/site-packages/webob/request.py", line 1291, in call_application
    app_iter = application(self.environ, start_response)
  File "/opt/onegov-applications/lib/python3.6/site-packages/depot/middleware.py", line 122, in __call__
    return environ.get('wsgi.file_wrapper', _FileIter)(self.file, _BLOCK_SIZE)
io.UnsupportedOperation: fileno
```
</details>
---

This is the juicy bit:

```python
File "/opt/onegov-applications/lib/python3.6/site-packages/onegov/file/integration.py", line 145, in render_depot_file
    FileServeApp(file, cache_max_age=3600 * 24 * 7))
  File "/opt/onegov-applications/lib/python3.6/site-packages/webob/request.py", line 1327, in send
    application, catch_exc_info=False)
  File "/opt/onegov-applications/lib/python3.6/site-packages/webob/request.py", line 1291, in call_application
    app_iter = application(self.environ, start_response)
  File "/opt/onegov-applications/lib/python3.6/site-packages/depot/middleware.py", line 122, in __call__
    return environ.get('wsgi.file_wrapper', _FileIter)(self.file, _BLOCK_SIZE)
io.UnsupportedOperation: fileno
```
I've noticed that this seems to be closely related to #128.

**Comment by jonashaag** [comment]
Do you know what's the type of self.file i.e. the first argument to the file wrapper? (Last line in the trace back)

**Comment by href** [comment]
I'll find out.

**Comment by href** [comment]
It's an instance of the `depot.io.local.LocalStoredFile` class, which is an `io.IOBase` descendant. You can find the class definition here: https://github.com/amol-/depot/blob/master/depot/io/local.py

**Comment by href** [comment]
Thanks 😃

**Comment by jonashaag** [comment]
Please try this and see if it works for you. I hope I haven't created any memory leaks or bugs. Python C API is terrible.

**Comment by href** [comment]
Unfortunately, I now see another error:

```python
  File "/opt/onegov-applications/lib/python3.6/site-packages/webob/response.py", line 534, in _body__get
    body = b''.join(app_iter)
IndexError
```

Do you need help setting up a test-case? I might be able to create a small test-script that provokes the error.

**Comment by jonashaag** [comment]
Yes, please. Maybe you can even stuff into `tests/filewrapper.py` (keeping webob an optional dependency of that script)

**Comment by jonashaag** [comment]
Oh, I made a trivial error, maybe this fixes it right away:

Remove the `PyErr_SetNone(PyExc_IndexError);` line in `filewrapper.c`.

**Comment by href** [comment]
That fixed it. Looks good in my tests now.
