### ISSUE TITLE
Packaging for nix

### ISSUE THREAD

**Issue by CMCDragonkai** [jonashaag/bjoern#140]
Hi I'm packaging this for Nix: https://github.com/NixOS/nixpkgs/pull/45557

I was wondering how do you run the tests for bjoern? Because it's not automated in the setup.py.

**Comment by jonashaag** [comment]
We don't really have automated tests

**Comment by jonashaag** [comment]
Theses are the only automated tests so far

https://github.com/jonashaag/bjoern/blob/master/tests/keep-alive-behaviour.py
https://github.com/jonashaag/bjoern/blob/master/tests/test_wsgi_compliance.py

**Comment by CMCDragonkai** [comment]
Do you just call them like scripts and is a 0 exit code considered success?

**Comment by jonashaag** [comment]
yep

**Comment by CMCDragonkai** [comment]
@jonashaag I ran the `keep-alive-behaviour.py` tests, and I keep getting these raised `ValueError: foo` and `ValueError: bar`, but it doesn't stop the test, it just gets reported. Is that meant to happen?

```
Traceback (most recent call last):
  File "tests/keep-alive-behaviour.py", line 15, in dispatcher
    return dispatcher.app(environ, start_response)
  File "tests/keep-alive-behaviour.py", line 118, in __call__
    raise ValueError('bar')
ValueError: bar
Traceback (most recent call last):
  File "tests/keep-alive-behaviour.py", line 15, in dispatcher
    return dispatcher.app(environ, start_response)
  File "tests/keep-alive-behaviour.py", line 112, in __call__
    raise ValueError('foo')
ValueError: foo
Traceback (most recent call last):
  File "tests/keep-alive-behaviour.py", line 15, in dispatcher
    return dispatcher.app(environ, start_response)
  File "tests/keep-alive-behaviour.py", line 112, in __call__
    raise ValueError('foo')
ValueError: foo
Traceback (most recent call last):
  File "tests/keep-alive-behaviour.py", line 15, in dispatcher
    return dispatcher.app(environ, start_response)
  File "tests/keep-alive-behaviour.py", line 118, in __call__
    raise ValueError('bar')
ValueError: bar
Traceback (most recent call last):
  File "tests/keep-alive-behaviour.py", line 15, in dispatcher
    return dispatcher.app(environ, start_response)
  File "tests/keep-alive-behaviour.py", line 118, in __call__
    raise ValueError('bar')
ValueError: bar
Traceback (most recent call last):
  File "tests/keep-alive-behaviour.py", line 15, in dispatcher
    return dispatcher.app(environ, start_response)
  File "tests/keep-alive-behaviour.py", line 112, in __call__
    raise ValueError('foo')
ValueError: foo
Traceback (most recent call last):
  File "tests/keep-alive-behaviour.py", line 15, in dispatcher
    return dispatcher.app(environ, start_response)
  File "tests/keep-alive-behaviour.py", line 118, in __call__
    raise ValueError('bar')
ValueError: bar
Traceback (most recent call last):
  File "tests/keep-alive-behaviour.py", line 15, in dispatcher
    return dispatcher.app(environ, start_response)
  File "tests/keep-alive-behaviour.py", line 118, in __call__
    raise ValueError('bar')
ValueError: bar
Running test 0: (0, 0, 0, 0, 0, 0)
Running test 1: (0, 0, 0, 1, 0, 0)
Running test 2: (0, 0, 1, 0, 0, 0)
Running test 3: (0, 0, 1, 1, 0, 1)
Running test 4: (0, 1, 0, 0, 0, 0)
Running test 5: (0, 1, 0, 1, 0, 0)
Running test 6: (0, 1, 1, 0, 0, 0)
Running test 7: (0, 1, 1, 1, 0, 0)
Running test 8: (1, 0, 0, 0, 0, 0)
Running test 9: (1, 0, 0, 1, 1, 1)
Running test 10: (1, 0, 1, 0, 0, 0)
Running test 11: (1, 0, 1, 1, 0, 1)
Running test 12: (1, 1, 0, 0, 0, 0)
Running test 13: (1, 1, 0, 1, 0, 0)
Running test 14: (1, 1, 1, 0, 0, 0)
Running test 15: (1, 1, 1, 1, 0, 0)
--- SUCCESS! ---
```

**Comment by CMCDragonkai** [comment]
Also this test seems to always succeed!?

**Comment by jonashaag** [comment]
Yes that's output from the tested server instance and is expected. 

You should be able to break the test by changing stuff in Bjoern's source code, otherwise that's a bug in the test!

**Comment by jonashaag** [comment]
You can try to adapt the test so that stderr is not in the output

**Comment by CMCDragonkai** [comment]
This is now done.
