### ISSUE TITLE
TypeError: can't pickle thread.lock objects

### ISSUE THREAD

**Issue by radiantone** [jonashaag/bjoern#148]
Hi,
  When I try to serialize a function in my Flask (WSGI) app it produces this error. But when I wrap my WSGI Flask app with another container (like Twisted) it works fine.

Thoughts?

**Comment by jonashaag** [comment]
Please paste a full traceback

**Comment by radiantone** [comment]
Traceback (most recent call last):
  File "/data/darren/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/data/darren/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/data/darren/anaconda2/lib/python2.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/data/darren/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/data/darren/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/data/darren/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "U/server/u/precog.py", line 3829, in federatedsimilar
    results = compute([get_google_partial(appid),get_ipcom_partial(appid), get_npl_partial(appid)], get=dask.get)
  File "/data/darren/anaconda2/lib/python2.7/site-packages/dask/base.py", line 206, in compute
    results = get(dsk, keys, **kwargs)
  File "/data/darren/anaconda2/lib/python2.7/site-packages/distributed/client.py", line 1919, in get
    resources=resources)
  File "/data/darren/anaconda2/lib/python2.7/site-packages/distributed/client.py", line 1882, in _graph_to_futures
    'tasks': valmap(dumps_task, dsk3),
  File "/data/darren/anaconda2/lib/python2.7/site-packages/toolz/dicttoolz.py", line 84, in valmap
    rv.update(zip(iterkeys(d), map(func, itervalues(d))))
  File "/data/darren/anaconda2/lib/python2.7/site-packages/distributed/worker.py", line 686, in dumps_task
    return {'function': dumps_function(task[0]),
  File "/data/darren/anaconda2/lib/python2.7/site-packages/distributed/worker.py", line 650, in dumps_function
    b = pickle.dumps(func)
  File "/data/darren/anaconda2/lib/python2.7/site-packages/distributed/protocol/pickle.py", line 51, in dumps
    return cloudpickle.dumps(x, protocol=pickle.HIGHEST_PROTOCOL)
  File "/data/darren/anaconda2/lib/python2.7/site-packages/cloudpickle/cloudpickle.py", line 900, in dumps
    cp.dump(obj)
  File "/data/darren/anaconda2/lib/python2.7/site-packages/cloudpickle/cloudpickle.py", line 234, in dump
    return Pickler.dump(self, obj)
  File "/data/darren/anaconda2/lib/python2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "/data/darren/anaconda2/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/data/darren/anaconda2/lib/python2.7/site-packages/cloudpickle/cloudpickle.py", line 360, in save_function
    self.save_function_tuple(obj)
  File "/data/darren/anaconda2/lib/python2.7/site-packages/cloudpickle/cloudpickle.py", line 508, in save_function_tuple
    save(f_globals)
  File "/data/darren/anaconda2/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/data/darren/anaconda2/lib/python2.7/pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/data/darren/anaconda2/lib/python2.7/pickle.py", line 687, in _batch_setitems
    save(v)
  File "/data/darren/anaconda2/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/data/darren/anaconda2/lib/python2.7/site-packages/cloudpickle/cloudpickle.py", line 360, in save_function
    self.save_function_tuple(obj)
  File "/data/darren/anaconda2/lib/python2.7/site-packages/cloudpickle/cloudpickle.py", line 508, in save_function_tuple
    save(f_globals)
  File "/data/darren/anaconda2/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/data/darren/anaconda2/lib/python2.7/pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/data/darren/anaconda2/lib/python2.7/pickle.py", line 687, in _batch_setitems
    save(v)
  File "/data/darren/anaconda2/lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/data/darren/anaconda2/lib/python2.7/site-packages/cloudpickle/cloudpickle.py", line 786, in save_reduce
    save(state)
  File "/data/darren/anaconda2/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/data/darren/anaconda2/lib/python2.7/pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/data/darren/anaconda2/lib/python2.7/pickle.py", line 687, in _batch_setitems
    save(v)
  File "/data/darren/anaconda2/lib/python2.7/pickle.py", line 306, in save
    rv = reduce(self.proto)
TypeError: can't pickle thread.lock objects

**Comment by radiantone** [comment]
Seems like a global lock is introduced somewhere by Bjoern

**Comment by jonashaag** [comment]
This doesn't look like it has anything to do with bjoern. Please try to reduce it to a minimal, reproducible example that you can share here.

**Comment by radiantone** [comment]
Ok, let me do that.

**Comment by radiantone** [comment]
Here's what I've discovered. When I try to pickle my function (call it FuncA) when my module loads, it pickles fine.

But if I try to pickle the same function inside a route function (call it FuncB) that was dispatched (by Bjoern) then FuncA no longer pickles.
